### ISSUE TITLE
Bug in description of ASCII85

### ISSUE THREAD

**Issue by mtx500** [mozq/dencode-web#6]
On https://dencode.com/string/ascii85, the second example shows 6F000000(16)
= 1214606444(10), which is wrong (copy-paste error from first example). Correct decimal value is 1862270976. The div/mod calculation of the second example is correct.

**Comment by mozq** [comment]
Fixed in https://github.com/mozq/dencode-web/commit/8e3f386e994d1a6954e40c0a2cad6e7efe738612 . Thank you for letting me know.
