### ISSUE TITLE
Small Caps Converter

### ISSUE THREAD

**Issue by wany-oh** [mozq/dencode-web#7]
Is it possible to add small caps converter? i.e. `abcdefghijklmnopqrstuvwxyz` to `ᴀʙᴄᴅᴇꜰɢʜɪᴊᴋʟᴍɴᴏᴘꞯʀꜱᴛᴜᴠᴡxʏᴢ`

Note: “LATIN LETTER SMALL CAPITAL X” does not exist and plain small letter `x` is used instead.

**Comment by mozq** [comment]
Let me consider it.

**Comment by mozq** [comment]
I have added “Font Style” converter and implemented “Small Capital” as one of the styles (ae5b481a4e6563465e014b2b83d271c5926aaf21). Please let me know if you have any comments.

https://dencode.com/string/font-style
