### ISSUE TITLE
Unix Timestamp: change [ms] and [s]

### ISSUE THREAD

**Issue by olfMombach** [mozq/dencode-web#9]
When inputting a timestamp like `1571979223` (or any other timestamp so far) the date shown in the "Date" section (and all related entries) is always wrong. It always shows a year of 1970 (minimum year for timestamp) and some month/day.

In comparison, when using `datetime.fromtimestamp(1571979223)` I get a result of `datetime.datetime(2019, 10, 25, 6, 53, 43)`, just like with e.g. https://www.epochconverter.com/ or any other timestamp converting service.

**Comment by olfMombach** [comment]
Just realized that it shows [ms] next to the timestamp option. Adding 3 zeros to the input then fixes it. So I guess this issue would be moot then. Although I would say most timestamps I see are in seconds, so there being an option to set it to seconds could be a useful feature. Gonne leave this here as an idea and let you do with it what you want

**Comment by mozq** [comment]
Let me consider.

**Comment by mozq** [comment]
@olfMombach,
I have changed the unit of UNIX time from milliseconds to seconds.
Milliseconds are still supported as decimal numbers. (1571979223999 -> 1571979223.999)
UNIX time now also supports nanoseconds. (1571979223.999999999)

This change has been deployed to https://dencode.com/ . Please let me know if you have any issues.

**Comment by olfMombach** [comment]
Works perfectly, thanks for the quick response!
